In [4]:
# 最近业务真切的遇到了数据分析的问题，来劲了，立马学习！

In [5]:
import numpy as np

Numpy 的基本索引和切片

In [2]:
# 本质上可以按照python的列表去理解

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
arr[5:8]=12

In [11]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [13]:
# 把标量值赋值给切片的时候，该值会自动传播（广播）到整个选区。和列表不同的地方在于，数据不会被复制，而是直接作用于源数组。
# 这样设计的原因来自于Numpy本身的定位，就是服务于处理大数据的，因此如果对于大数据的复制而言会带来巨大的性能和内存开销问题。

In [14]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [15]:
arr2[2]

array([7, 8, 9])

In [16]:
# 如果要取各个元素值，有两种方式，如下：

In [17]:
arr2[2][2]

9

In [18]:
arr2[2,2]

9

切片索引

In [20]:
# 一维的和python列表差不多，但是二维稍微不同

In [21]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 也可以一次传入多个切片，就像传入多个索引一样

In [22]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [23]:
# 此外，通过将索引和切片混合，也可以得到低维度的切片

In [24]:
arr2[1,:2]

array([4, 5])

布尔型索引

In [25]:
data = np.random.randn(7,4)

In [26]:
data

array([[ 0.20157447,  2.16503028,  0.28984015, -0.92532928],
       [ 1.71393821, -0.93543438, -0.97475472, -0.60412759],
       [-0.10674814, -0.04983479, -0.84518115, -1.13898453],
       [ 0.29843406,  1.26545331,  0.88754411,  0.81576779],
       [-1.05138437, -0.71185462,  0.07391401, -0.39673357],
       [-0.23764407, -0.58336328,  0.52102608,  0.1065046 ],
       [ 0.17113445, -0.73168734, -0.37572017,  0.05816269]])

In [27]:
#通过布尔数组设置值是一种常用的手段，将data中所有小于0的负值设置为0可以如下操作：

In [28]:
data[data<0]=0

In [29]:
data

array([[0.20157447, 2.16503028, 0.28984015, 0.        ],
       [1.71393821, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.29843406, 1.26545331, 0.88754411, 0.81576779],
       [0.        , 0.        , 0.07391401, 0.        ],
       [0.        , 0.        , 0.52102608, 0.1065046 ],
       [0.17113445, 0.        , 0.        , 0.05816269]])

花式索引

In [ ]:
# 花式索引是python的一个术语，是利用整数数组进行索引

In [36]:
arr = np.empty((8,4))

In [32]:
for i in range(8):
    arr[i] = i

In [40]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
# 为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可。

In [38]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [41]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [43]:
arr = np.arange(32).reshape((8,4))

In [44]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [45]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])