### Numpy 数组和矢量计算

大多数提供科学计算的包都是使用Numpy的数组作为基础建构基础

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.26870775,  0.21790995,  0.06429363],
       [-1.27093489,  0.96693703,  0.95017497]])

In [4]:
data * 10

array([[ -2.68707746,   2.17909955,   0.64293629],
       [-12.70934885,   9.66937028,   9.50174969]])

In [5]:
data + data   # 每个元素和自身相加

array([[-0.53741549,  0.43581991,  0.12858726],
       [-2.54186977,  1.93387406,  1.90034994]])

ndarray 包含一个shape和一个dtype

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

key: 精通面向数组的编程和思维方式

### 创建

创建数组，用array函数，接受一切序列型对象

In [9]:
data1 = [6,7.5,8,0,1] 
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
arr1.dtype

dtype('float64')

In [15]:
data2 = [[1,2,3,4],[4,5,6,7]]
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [17]:
arr2.ndim # 属性

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr2.dtype

dtype('int32')

zeros 和 ones分别可新建数组

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.empty返回的是未初始化的垃圾值,相当于是只分配内存空间

In [22]:
np.arange(15)   #python内置函数range的数组版 ，返回的是ndarray而非list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr1 = np.array([1,2,3])

In [24]:
arr1.dtype

dtype('int32')

In [25]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [26]:
arr1

array([1., 2., 3.])

ndarray的astype方法则可以明确将一个数组从一个dtype转换成另一个dtype

In [31]:
float_arr1 = arr1.astype(np.float32)

In [32]:
float_arr1.dtype

dtype('float32')

注：Numpy的字符串数据大小固定，因此在使用string类型时，若截取，不会发生警告。